name: Deploy Multi Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            set -e
            cd /opt || true
            rm -rf multi-app-cicd
            git clone git@github.com:yanyan-handayani/multi-app-cicd.git
            cd multi-app-cicd
            docker compose down || true
            docker compose up -d --build

  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e
            cd /opt || true
            rm -rf multi-app-cicd
            git clone git@github.com:yanyan-handayani/multi-app-cicd.git
            cd multi-app-cicd
            docker compose down || true
            docker compose up -d --build