name: Deploy Multi Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GCP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            set -e
            if [ ! -f /opt/multi-app-cicd/scripts/deploy-gcp.sh ]; then
              sudo mkdir -p /opt/multi-app-cicd
              sudo chown -R $USER:$USER /opt/multi-app-cicd
              if [ -d /opt/multi-app-cicd/.git ]; then
                git -C /opt/multi-app-cicd pull --ff-only
              else
                git clone git@github.com:yanyan-handayani/multi-app-cicd.git /opt/multi-app-cicd
              fi
            fi
            bash /opt/multi-app-cicd/scripts/deploy-gcp.sh

  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e
            if [ ! -f /opt/multi-app-cicd/scripts/deploy-aws.sh ]; then
              sudo mkdir -p /opt/multi-app-cicd
              sudo chown -R $USER:$USER /opt/multi-app-cicd
              if [ -d /opt/multi-app-cicd/.git ]; then
                git -C /opt/multi-app-cicd pull --ff-only
              else
                git clone git@github.com:yanyan-handayani/multi-app-cicd.git /opt/multi-app-cicd
              fi
            fi
            bash /opt/multi-app-cicd/scripts/deploy-aws.sh